config/routes.rb
Rails.application.routes.draw do
  root 'guides#index'

  resources :guides do
    resources :steps
  end
end

app/models/guide.rb
class Guide < ActiveRecord::Base
  has_many :steps, dependent: :destroy
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :guide
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  def index
    @guides = Guide.all
  end

  def show
    @guide = Guide.find(params[:id])
    @step = Step.new
  end

  def new
    @guide = Guide.new
  end

  def create
    @guide = Guide.new(guide_params)

    if @guide.save
      redirect_to guide_path(@guide), notice: 'Guide created! Add steps below.'
    else
      render :new
    end
  end

  def edit
    @guide = Guide.find(params[:id])
  end

  def update
    @guide = Guide.find(params[:id])

    if @guide.update(guide_params)
      redirect_to @guide, notice: "Guide updated!"
    else
      render :edit
    end
  end

  def destroy
    @guide = Guide.find(params[:id])
    @guide.destroy
    redirect_to guides_path
  end

  private

  def guide_params
    params.require(:guide).permit(:title)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def create
    @guide = Guide.find(params[:guide_id])
    @step = @guide.steps.build(step_params)

    if @step.save
      redirect_to @guide, notice: 'Step added!'
    else
      render 'articles/#{@article}.id'
    end
  end

  def edit
    @guide = Guide.find(params[:guide_id])
    @step = @guide.steps.find(params[:id])
  end

  def update
    @guide = Guide.find(params[:guide_id])
    @step = @guide.steps.find(params[:id])

    if @step.update(step_params)
      redirect_to @guide, notice: 'Step updated!'
    else
      render :edit
    end
  end

  def destroy
    @guide = Guide.find(params[:guide_id])
    @step = @guide.steps.find(params[:id])

    @step.destroy
    redirect_to @guide, notice: 'Step deleted!'
  end

  private

  def step_params
    params.require(:step).permit(:action)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_form.html.erb
<%= form_for(@guide) do |f| %>
  <% if @guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% @guide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/guides/edit.html.erb
<h1>Editing guide</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide %> |
<%= link_to 'Back', guides_path %>

app/views/guides/index.html.erb
<h1>Listing guides</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guides.each do |guide| %>
      <tr>
        <td><%= link_to guide.title, guide %></td>
        <td><%= link_to 'Show', guide %></td>
        <td><%= link_to 'Edit', edit_guide_path(guide) %></td>
        <td><%= link_to 'Destroy', guide, method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide', new_guide_path %>

app/views/guides/new.html.erb
<h1>New guide</h1>

<%= render 'form' %>

<%= link_to 'Back', guides_path %>

app/views/guides/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @guide.title %></h1>

<% @guide.steps.each do |step| %>
  <ul>
    <li>
      <%= step.action %>
      <%= link_to 'Edit', edit_guide_step_path(@guide, step) %>|
      <%= link_to 'Destroy', guide_step_path(@guide, step), method: :delete,
        data: { confirm: 'Are you sure?' }%>
    </li>
  </ul>
  <br/>
<% end %>

<%= render 'steps/form' %>

<%= link_to 'Edit', edit_guide_path(@guide) %> |
<%= link_to 'Back', guides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HowToSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@guide, @step] do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@step.errors.count, "error") %>
        prohibited this step from being saved:
      </h2>
      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='actions'>
    <%= f.label :action %>
    <%= f.text_field :action %>
  </div>
  <div class='actions'>
    <%= f.submit @step.new_record? ? 'Add step' : 'Update step' %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @guide %> |
<%= link_to 'Back', guides_path %>